### ISSUE TITLE
hiding IP from moderators

### ISSUE THREAD

**Issue by ser** [pit-PL/bootlike#2]
Hi,
continuing improvements, another switch in _config.html which would hide IPs from moderators in MCP. In current strict GDPR laws there is no need for mods to see any IPs to properly make their job.

**Comment by pit-PL** [comment]
What your mean by "in MCP", what  URLs your are talking about?

**Comment by ser** [comment]
![obraz](https://user-images.githubusercontent.com/231537/122238674-8725c280-ceea-11eb-9db2-0468bb9dbc9c.png)

"User IP" column should be removed entirely from the view for moderators. Otherwise they have access to sensitive data and should sign GDPR responsibilities. Of course not by default, but it would be super useful to have such an option in _config

**Comment by pit-PL** [comment]
Done.

The reason I asked for details is because the main page is not the only one where moderators can see users IPs.

**Comment by ser** [comment]
All pages where moderators can see IP should have that column removed IMHO.

**Comment by pit-PL** [comment]
OK, removed from:
mcp_front
mcp_logs
mcp_notes_user
mcp_post
