### ISSUE TITLE
inconsequent layout

### ISSUE THREAD

**Issue by ser** [pit-PL/bootlike#3]
In viewforum the navigation arrow is very clear and easy to click:
![Zrzut ekranu-20210622003352-834x474](https://user-images.githubusercontent.com/231537/122804149-b7f26700-d2f1-11eb-982e-f66122c5304e.png)
but in main index it's small and in between other text, hard to navigate:
![Zrzut ekranu-20210622003332-864x546](https://user-images.githubusercontent.com/231537/122804243-dbb5ad00-d2f1-11eb-88dc-db60a2b00817.png)
My comment is that the main view should look the same as the forum one, with an arrow moved to the right and much bigger.

**Comment by pit-PL** [comment]
Thanks for reporting! I will look into this tomorrow.

**Comment by ser** [comment]
it looks good now, thanks 💯
