### ISSUE TITLE
search_results problems

### ISSUE THREAD

**Issue by ser** [pit-PL/bootlike#4]
Hi, in last post column you have copied by mistake ```searchresults.TOPIC_AUTHOR_FULL``` instead of ```earchresults.LAST_POST_AUTHOR_FULL``` 

I am not sending PR because I am sure you are about to upgrade to BS 5.1 soon 👍🏿

**Comment by pit-PL** [comment]
Bug fixed, thanks for reporting!

**Comment by ser** [comment]
Thanks, it works great now.
