### ISSUE TITLE
Moderators button displays quickmod button

### ISSUE THREAD

**Issue by steevo** [pit-PL/bootlike#7]
![moderators](https://user-images.githubusercontent.com/6705053/207161500-8ce0f9ff-92bd-482c-8d01-a080ce1937ff.png)
![quickmod](https://user-images.githubusercontent.com/6705053/207161506-1410f6e8-3327-4d51-9c9b-6f558164fa4a.png)

In the viewtopic, the button that would display moderators list displays the quickmod actions.
Quickmod button is ok.
So we have two different buttons that display the same thing. And it's not possible to see moderators names

**Comment by pit-PL** [comment]
This issue also applies to the board index and view forum  page. Thanks for reporting.
https://github.com/pit-PL/bootlike/commit/d26a194de3c843a442237c346645b06c2bb270e4
https://github.com/pit-PL/bootlike/commit/c8290e21322ddf9c3fa4cc6a39e798ca39e3c01b
https://github.com/pit-PL/bootlike/commit/9950b4ed5860878ecabe59c436aa74a94f692e66

**Comment by steevo** [comment]
Thanks for that. It works now !
